### ISSUE TITLE
fingerprint unlock in lock screen

### ISSUE THREAD

**Issue by nollidnosnhoj** [noctalia-dev/noctalia-shell#137]
I have a framework 16 laptop with a fingerprint reader, and with fprintd enabled, the lock screen does not unlock with fingerprint. 

Now after I enter my password, the lock screen will say execute. Usually I would just click enter again to unlock the screen, but you could also use your fingerprint to unlock it.

However, I would expect the fingerprint to use unlock it automatically with the fingerprint, similar to how hyprlock worked. 

I can look into this when I have time, and it could be possible that I have some sort of misconfiguration in my nixos config

nixos config: https://github.com/nollidnosnhoj/.nixos/blob/65c15ef3240157a3d1d7b8795e70eb444b0a4a04/hosts/framework16/default.nix#L68

**Comment by nollidnosnhoj** [comment]
My theory is that the PAM context starts when you click enter on the keyboard. Because if I type anything that's not my password (as long as it's not an empty string), it will wait for me to place finger on reader (based on the log). Once i place my finger, it will authenticate me. 

I'm wondering if starting the pam context when the lockscreen component shows will allow to use fingerprint. (Have not tested this out. Not sure how to do this in QML). My theory is that when starting the PAM context when the lockscreen shows up will allow the user to place fingerprint. If the user does not have fingerprint (password authentication), then the initial PAM context will fail, and then we can start another pam context when the user presses enter. 

```
 DEBUG qml: [20250824-134240]    LockContext Starting PAM authentication for user: kopa
 DEBUG qml: [20250824-134240]    LockContext PAM message: Place your right index finger on the fingerprint reader isError: false responseRequired: false
 DEBUG qml: [20250824-134241]    LockContext PAM completed with result: 0
 DEBUG qml: [20250824-134241]    LockContext Authentication successful
```

**Comment by nollidnosnhoj** [comment]
I came up with a solution by starting a PAM connection when the lock screen component is completed, and only respond to the pam connection if the password is entered (since for fingerprint authentication, the password won't be entered).

However, it kinda of feels hacky, especially trying to make password auth work alongside fingerprint auth. 

https://github.com/nollidnosnhoj/Noctalia/blob/lockscreen-fprint-compatible/Modules/LockScreen/LockContext.qml

not sure if there's a way to know what auth method is being used in the PamContext. Also don't know whether to add a configuration to enable fingerprint authentication would be a better option.

EDIT: After some thought, I do not prefer my solution. It's not that scalable for other PAM methods. I wonder if there is a simpler way using the current PAMContext.

**Comment by Ly-sec** [comment]
Hey there, sadly I do not have access to a finger print reader to test it. Perhaps someone else has the ability to test/try stuff. If you do figure out a way to make both work, that would be awesome ❤️!

**Comment by nollidnosnhoj** [comment]
Yeah, I can look into it more when I get the chance. However, it's not a huge issue right now.

**Comment by matejc** [comment]
Does this help? https://github.com/noctalia-dev/noctalia-shell/pull/229

**Comment by matejc** [comment]
> I'm wondering if starting the pam context when the lockscreen component shows will allow to use fingerprint.

Why? I think that is a bad idea, since PAM itself times out and switches automatically to password authentication based on the /etc/pam.d/login, that said, you could disable pam_unix pam auth module in that file (which is out of the scope of noctalia-shell), but keeping the pam_fprintd auth module, and make a loop that triggers the pam module (and therefore the fingerprint reader) every time it times out, but that not a clean solution. Not to mention the strain on the fingerprint device being constantly turned on. At least that what I figured...

Basically you need a good trigger for fingerprint init, sending an empty password response by pressing Enter key in the input box is one option, and is widely used in conjunction with PAM

**Comment by nollidnosnhoj** [comment]
I'm not familiar with how PAM works so any suggestions would be better than mine.

Unfortunately, I did not have time to look into this more, or check out your PR. However, when I get the chance (hopefully this weekend), I can check it out.

**Comment by ItsLemmy** [comment]
Can you try again and report back ? We merged a PR regarding this. Thanks

**Comment by nollidnosnhoj** [comment]
Sorry for the late reply. Tried it out, and it worked. When I typed my password, it asked to place finger onto reader.

**Comment by hboetes** [comment]
I also have a fingerprint reader. To unlock the screen I have to hit enter and then use the fingerprint reader. qs/ns does not ask me to put my finger on the reader, it just asks me for my password.

Here is the log of the transaction, so lock->hit enter->put finger on reader.
```
  INFO qml: [20251212-205954]    LockContext Starting PAM authentication for user: han
quickshell.service.pam.subprocess: Waiting for parent confirmation...
quickshell.service.pam.subprocess: Starting pam session for user "han" with config "login" in dir "/etc/pam.d"
quickshell.service.pam.subprocess: Relaying pam message: "Place your right index finger on the fingerprint reader" echo: 1 error: 0 responseRequired: 0
  INFO qml: [20251212-205955]    LockContext PAM message: Place your right index finger on the fingerprint reader isError: false responseRequired: false
quickshell.service.pam.subprocess: Authenticated successfully.
  INFO qml: [20251212-205957]    LockContext PAM completed with result: 0
  INFO qml: [20251212-205957]    LockContext Authentication successful
  WARN qt.qpa.wayland.textinput: virtual void QtWaylandClient::QWaylandTextInputv3::disableSurface(wl_surface*) Try to disable surface 0x7fdd8ad3f200 with focusing surface 0x7fdda08e0ac0
```

EDIT: using the latest code from git.

**Comment by Redrield** [comment]
On my nixos-on-framework 16 install, fingerprint auth on the lock screen still isn't working. Looking into the logs, it's only looking for pam_fprintd.so in the main PAM path in the nix store, while the file is under a different package.
```
Dec 15 15:59:42 Artemis quickshell[271192]: PAM unable to dlopen(/nix/store/llsdrdpgdmrhnif0jcb283kv78dw4iib-linux-pam-1.7.1/lib/security/pam_fprintd.so): /nix/store/llsdrdpgdmrhnif0jcb283kv78dw4iib-linux-pam-1.7.1/lib/security/pam_fprintd.so: cannot open shared object file: No such file or directory9
Dec 15 15:59:42 Artemis quickshell[271192]: PAM adding faulty module: /nix/store/llsdrdpgdmrhnif0jcb283kv78dw4iib-linux-pam-1.7.1/lib/security/pam_fprintd.so
Dec 15 15:59:42 Artemis quickshell[271192]: PAM _pam_init_handlers: no default config other
```

(It should be looking for the library at `/nix/store/i5y8wmchcv6mwalz0rxwikra362jqyi2-fprintd-1.94.5/lib/security/pam_fprintd.so`).

I'm not sure whether this is a problem in my config or not, since hyprlock never ran into this problem. 

The module in my config that sets up noctalia-shell is [here](https://codeberg.org/Redrield/nix-config/src/branch/main/config/desktops/noctalia.nix). Would appreciate suggestions as to whether this is a config problem of mine or not

**Comment by Jack-Chronicle** [comment]
Also having problems logging in with fingerprint auth, can login with password just fine but can't with fingerprint due to it failing when no password is entered

If letting "press enter when no password" go to fingerprint auth is something that you would prefer to avoid, then adding a fingerprint auth button would also be a good alternative

**Comment by rober-m** [comment]
Also on NixOS, Framework 13. I can confirm that my fingerprint auth works on hyprlock, but not on noctalia.

**Comment by hboetes** [comment]
@Jack-Chronicle 
> If letting "press enter when no password" go to fingerprint auth is something that you would prefer to avoid, then adding a fingerprint auth button would also be a good alternative

gdm solves this practically with something like this:

`enter your password (or press the fingerprint scanner)`

**Comment by Jack-Chronicle** [comment]
> [@Jack-Chronicle](https://github.com/Jack-Chronicle)
> 
> > If letting "press enter when no password" go to fingerprint auth is something that you would prefer to avoid, then adding a fingerprint auth button would also be a good alternative
> 
> gdm solves this practically with something like this:
> 
> `enter your password (or press the fingerprint scanner)`

I'm actually using swaylock-effects as my lock screen currently which has been working fine, just would like to get the noctalia lockscreen working for a more cohesive look
