### ISSUE TITLE
[Bug]: Quickshell crash on opening windows [Hyprland]

### ISSUE THREAD

**Issue by fuma-afk** [noctalia-dev/noctalia-shell#239]
Description:
Getting a crash from quickshell randomly when opening windows on hyprland. It doesn't happen all the times but it seems to be happening only when i open windows and it's not tied to a specific app since it happened with kitty, zen browser and a steam game launch window so far.
It doesn't keep happening afterward for a while. 

Steps to Reproduce:
not sure,  It seems to be happening at random, but it's consistent on both my desktop and laptop since noctalia 2.6
wasn't happening before

Expected Behavior
not crash

Screenshots

<img width="922" height="233" alt="Image" src="https://github.com/user-attachments/assets/3b27f26c-69cf-4e2e-a95e-df634ace756a" />

Environment
- Distro: NixOs
- Compositor: Hyprland
- Noctalia-shell Version: 2.7

Additional Context
this seems similar to what was happening when closing the last window on the active workspace a while back, only it happens when opening window now but it's completely random. It does 't seem to be happening as often.

i already tried deleting settings and cache folder just to be sure and upgrade from 2.6 when it first started happening to 2.7.

**Comment by Ly-sec** [comment]
Totally forget to answer!
The issue should be fixed (hopefully). Can you let me know if it works now?

**Comment by fuma-afk** [comment]
no worries it doesn't happen very often

i think i have had a crash this very morning but i'm not sure if i was still on 2.7 or 2.8  (100% not 2.6) because it was a rough morning and i updated both my desktop and laptop at a certain point but not sure when.

i'll let you know if it happens in the next few days of use

**Comment by Ly-sec** [comment]
> no worries it doesn't happen very often
> 
> i think i have had a crash this very morning but i'm not sure if i was still on 2.7 or 2.8 (100% not 2.6) because it was a rough morning and i updated both my desktop and laptop at a certain point but not sure when.
> 
> i'll let you know if it happens in the next few days of use

Okay uhm can you perhaps provide some sort of logs from the crash (or when it happens the next time)?

**Comment by ItsLemmy** [comment]
Logs are saved in : /run/user/1000/quickshell/by-id/

**Comment by fuma-afk** [comment]
> > no worries it doesn't happen very often
> > i think i have had a crash this very morning but i'm not sure if i was still on 2.7 or 2.8 (100% not 2.6) because it was a rough morning and i updated both my desktop and laptop at a certain point but not sure when.
> > i'll let you know if it happens in the next few days of use
> 
> Okay uhm can you perhaps provide some sort of logs from the crash (or when it happens the next time)?

Speak of the devil...
i was just saying: "course i can" and as i opened my browser it happened again.

here:
https://drive.google.com/drive/folders/1sgqD4kGb8_BmKt98m6AHHcfxPyRXKReu?usp=sharing
you can get both crash istances.

the folders contain what was inside the path: /run/user/1000/quickshell/by-id/
inside each folder there iz a 7z archive with the content of ~/.cache/quickshell/crash, which accordingly to the log containes additional informations

sorry for the drive link but it's a lot of files!

**Comment by Ly-sec** [comment]
I just pushed a **possible** fix, it's hard to tell given it's random. Can you please pull the main branch and see if it happens again?

**Comment by fuma-afk** [comment]
It's truly random, haven't had it for about 3 hours and then bam twice in a row
Anyway sure, i just upgraded to latest source. Using it now and will let you know if it happens again!

ty for your work!

**Comment by fuma-afk** [comment]
it's been a full day of work where i opened all kind of stuff and never encountered a crash.

i think we can mark this as solved and, if it comes back, i'll post again

Thank you!

**Comment by ItsLemmy** [comment]
Awesome! thank you for reporting back!

**Comment by fuma-afk** [comment]
unfortunately this is still happening for some reason,

just happened twice, once when opening vlc the other when opening kde iso writer.
i can give you the logs if you like but it's likely the same stuff of last time.

**Comment by Ly-sec** [comment]
Urgh :/ but it does seem like it's much more rare now. I'm wondering if it's a Noctalia issue or an actual Quickshell issue or perhaps something very different 

I'm wondering are you using the quickshell flake or how did you install quickshell?

**Comment by fuma-afk** [comment]
Using the flake.
It could be a quickshell issue as every week roughly i update my whole system and thus, quickshell.

here a bunch of infos about the version and environment:
===== Build Information =====
Git Revision: 6eb12551baf924f8fdecdd04113863a754259c34
Buildtime Qt Version: 6.9.2
Build Type: RelWithDebInfo
Compiler: Clang (19.1.7)
Complie Flags: 

Build configuration:
  Distributor: Official-Nix-Flake
  Distributor provided debuginfo: TRUE
  Disable precompild headers (dev): OFF

it's super strange i haven't had a crash for about 24 hours and today all of a sudden 3-4 crashes in a row. so weird
one as i opened my first app, and the rest totally unrelated in the middle of nowhere with other applications.

i wonder if it's something about the task manager/information window... i could try to disable those

**Comment by Ly-sec** [comment]
Yeah it would be neat if you could try and go very minimal with the widgets and slowly introduce them back until it crashes again or something. Currently it's rather hard to fix since we don't know what's causing this issue.

**Comment by fuma-afk** [comment]
haven't had a single crash since, after simply removing the active window widget so i guess that's that,

And after using the taskbar, i like it more this way so i guess it's closed for me :)

I'll leave it open in case you want to take a look at it still, otherwise i would consider the matter concluded!

**Comment by ItsLemmy** [comment]
I have refactored a bit how we handle Hyprland vs Niri.   If you can, please get the latest code, re-add the active window, and be our guinea pig for a bit ? :)

**Comment by fuma-afk** [comment]
Hey!

Sure thing!

 but i will be unable to do it for the next 2-3 days as i'm away from home
and without any device to actually test it.

Ty in the meantime

Il ven 19 set 2025, 20:51 Lemmy ***@***.***> ha scritto:

**Comment by ItsLemmy** [comment]
It's fine, report back whenever you can :P

**Comment by fuma-afk** [comment]
it's been almost 3-4 days without a crash.

Closed for me

Ty!
